config/routes.rb
Rails.application.routes.draw do

  resources :playground_stuffs
  root 'static_pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      patch :increment
      patch :clear
    end
    resources :life_events, only: [:index, :new, :create]
  end

  resources :life_events, only: [:show, :edit, :update, :destroy]
  resources :students
  resources :journals, only: [:index, :show]
  resources :journal_entries

  resources :schools
  resources :checkpoints
  resources :goal_steps
  resources :goals

  resources :playgroundstuffs, only: [:index, :show, :edit, :update]

  get 'import_csv', to: 'users#import_csv'
  patch 'import_csv', to: 'users#update_csv'
  get 'import_csv2', to: 'users#import_csv2'
  patch 'import_csv2', to: 'users#update_csv2'

  get 'chart_fun', to: 'users#chart_fun'

  get 'calendar_test', to: 'users#calendar_test'
  get 'my_calendar_test', to: 'users#my_calendar_test'

  get 'hook', to: 'static_pages#hook'
  get 'run_hook', to: 'static_pages#run_hook'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @playground_stuff = PlaygroundStuff.the_singleton
  end

  def hook; end

  def run_hook
    hook_msg = hook2
    redirect_to hook_path, notice: hook_msg
  end

  private

  # returns students and users that don't have a school (and therefore
  # break The Playground)
  def hook2
    sch1 = School.first

    arr1 = []
    Student.all.each do |each_student|
      if each_student.school.blank?
        arr1.push each_student.name
        each_student.school = sch1
        each_student.save
      end
    end
    str1 = "Missing a school - Fixed these STUDENTS: "
    str1 += arr1.to_s

    arr2 = []
    User.all.each do |each_user|
      if each_user.school.blank?
        arr2.push each_user.name
        each_user.school = sch1
        each_user.save
      end
    end
    str1 += "; Fixed these USERS too: "
    str1 += arr2.to_s
    str1
  end

  # make sure each student and user has a non-nil school
  def hook1
    school1 = School.first

    # for all students, set school_id to 1 if nil
    num_students = 0
    Student.all.each do |each_student|
      if each_student.school.blank?
        each_student.school = school1
        each_student.save
        num_students += 1
      end
    end

    # for all students, set school_id to 1 if nil
    num_users = 0
    User.all.each do |each_user|
      if each_user.school.blank?
        each_user.school = school1
        each_user.save
        num_users += 1
      end
    end

    # construct and return helpful hook message
    msg = "hook1: updated school for " + helpers.pluralize(num_students, "student") +
          ", " + helpers.pluralize(num_users, "user")
    msg
  end

end

app/views/static_pages/home.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<span id="notice" class="float-right"><%= notice %></span>

<!-- header: title -->
<h3 class="mb-4">
  <small><i class="far fa-smile mr-2 text-success"></i></small>
  The Playground
</h3>

<p>
  Test things first on The Playground.
  <i class="fas fa-question-circle ml-2 text-secondary"
     data-toggle="tooltip" data-placement="bottom"
     title="The playground is FUN. Yow!"></i>
  <br>
  play first&trade;...yow, bill
</p>

<hr>

<p class="mt-4 mb-0">
  Playground stuff:
</p>
<ul>
  <li>
    <i><%= @playground_stuff.fun_message %></i>
  </li>
  <li>
    Current: <span class="font-weight-bold"><%= @playground_stuff.cur_user.name %></span> from
    <span style="color: <%= @playground_stuff.cur_school.color %>;"><%= @playground_stuff.cur_school.name %></span>, student:
    <%= @playground_stuff.cur_student&.name %>.
  </li>
  <li>
    Edit:
    <%= link_to 'Playground stuff', playground_stuffs_path %>
  </li>
</ul>

<p class="mt-5">
  1. All index pages:
  &nbsp;
  <%= link_to 'All Schools', schools_path %>
  &nbsp; | &nbsp;
  <%= link_to 'All Users', users_path %>
  &nbsp; | &nbsp;
  <%= link_to 'All Students', students_path %>
  &nbsp; | &nbsp;
  <%= link_to 'All Goals', goals_path %>
  &nbsp; | &nbsp;
  <%= link_to 'All Goal steps', goal_steps_path %>
  &nbsp; | &nbsp;
  <%= link_to 'All Checkpoints', checkpoints_path %>
</p>

<p class="mt-4">
  2. Testing:
  &nbsp; &nbsp;
  <%= link_to 'Import CSV', import_csv_path, class: "btn btn-outline-secondary" %>
  &nbsp; &nbsp;
  <%= link_to 'Chart fun', chart_fun_path, class: "btn btn-outline-info" %>
  &nbsp; &nbsp;
  <%= link_to 'My Calendar', my_calendar_test_path, class: "btn btn-outline-warning" %>
  &nbsp; &nbsp;
  <%= link_to 'Calendar', calendar_test_path, class: "btn btn-outline-primary" %>
  &nbsp; &nbsp;
  <%= link_to 'Webpack test', "#", id: "webpack-test", class: "btn btn-outline-danger" %>
  &nbsp; &nbsp;
  <%= link_to 'Webpack test #2', "#", id: "webpack-test2", class: "btn btn-outline-danger" %>
</p>

<p class="mt-4">
  3. Etc
</p>
<p>
  Run some hook code, <%= link_to 'Hook page', hook_path %>
</p>
<p>
  Old - <%= link_to 'All Journals', journals_path %>
</p>
<p>
  Bill - your laptop says hello. &nbsp; <i class="fas fa-laptop"></i>
</p>
<p>
  This image is in the asset pipeline.
  <%= image_tag "crayons2.jpg", style: 'height:128px;'%>
</p>

    </div>
  </div>
</div>

<%= javascript_pack_tag 'hello', 'data-turbolinks-track': 'reload' %>

app/views/static_pages/hook.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<span id="notice" class="text-info"><%= notice %></span>

<!-- header: title -->
<h3 class="mt-4 mb-4">
  Hook page
</h3>

<p>
  Run a little code.
</p>
<p class="mx-5 text-muted">
  Hook #2 - print students and users that don't have a school (and crash The Playground)
</p>
<p class="mx-5">
  <%= link_to 'Run hook2', run_hook_path,
              class: "btn btn-sm btn-outline-secondary" %>
</p>

<!-- nav: breadcrumbs -->
<%= render 'shared/breadcrumbs', cur_page: 'Hook page' %>