config/routes.rb
Rails.application.routes.draw do

  resources :playground_stuffs
  root 'static_pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      patch :increment
      patch :clear
    end
    resources :life_events, only: [:index, :new, :create]
  end

  resources :life_events, only: [:show, :edit, :update, :destroy]
  resources :students
  resources :journals, only: [:index, :show]
  resources :journal_entries

  resources :schools
  resources :checkpoints
  resources :goal_steps
  resources :goals

  resources :playgroundstuffs, only: [:index, :show, :edit, :update]

  get 'import_csv', to: 'users#import_csv'
  patch 'import_csv', to: 'users#update_csv'
  get 'import_csv2', to: 'users#import_csv2'
  patch 'import_csv2', to: 'users#update_csv2'

  get 'chart_fun', to: 'users#chart_fun'

  get 'calendar_test', to: 'users#calendar_test'
  get 'my_calendar_test', to: 'users#my_calendar_test'

  get 'hook', to: 'static_pages#hook'
  get 'run_hook', to: 'static_pages#run_hook'

end

app/models/checkpoint.rb
class Checkpoint < ApplicationRecord
  belongs_to :school, optional: true
  belongs_to :student, optional: true

  validates :check_at, presence: true
  validates :handle, presence: true, length: {maximum: 16}
  validates :description, presence: true

  scope :from_past, -> { where("check_at < ?", Date.today) }
  scope :in_future, -> { where("check_at >= ?", Date.today) }

  def self.all_past_checkpoints
    Checkpoint.all.from_past.order("check_at ASC")
    # Student.active.order("handle ASC")
  end

  def self.all_future_checkpoints
    Checkpoint.all.in_future.order("check_at ASC")
  end

end

app/controllers/checkpoints_controller.rb
class CheckpointsController < ApplicationController
  before_action :set_checkpoint, only: %i[ show edit update destroy ]

  # GET /checkpoints or /checkpoints.json
  def index
    @checkpoints = Checkpoint.all_future_checkpoints
    @past_checkpoints = Checkpoint.all_past_checkpoints
  end

  # GET /checkpoints/1 or /checkpoints/1.json
  def show
  end

  # GET /checkpoints/new
  def new
    @checkpoint = Checkpoint.new
  end

  # GET /checkpoints/1/edit
  def edit
  end

  # POST /checkpoints or /checkpoints.json
  def create
    @checkpoint = Checkpoint.new(checkpoint_params)
    @checkpoint.school = School.first

    respond_to do |format|
      if @checkpoint.save
        format.html { redirect_to @checkpoint, notice: "Checkpoint was successfully created." }
        format.json { render :show, status: :created, location: @checkpoint }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @checkpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkpoints/1 or /checkpoints/1.json
  def update
    respond_to do |format|
      if @checkpoint.update(checkpoint_params)
        format.html { redirect_to @checkpoint, notice: "Checkpoint was successfully updated." }
        format.json { render :show, status: :ok, location: @checkpoint }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @checkpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkpoints/1 or /checkpoints/1.json
  def destroy
    @checkpoint.destroy
    respond_to do |format|
      format.html { redirect_to checkpoints_url, notice: "Checkpoint was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkpoint
      @checkpoint = Checkpoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def checkpoint_params
      params.require(:checkpoint).permit(:check_at, :handle, :description)
    end
end

app/helpers/checkpoints_helper.rb
module CheckpointsHelper
end

app/views/checkpoints/_form.html.erb
<%= form_with(model: checkpoint, local: true) do |form| %>

  <%= render 'shared/form_error', the_object: checkpoint %>

<style>
  .bg-white-flatpickr { background-color: white !important; }
</style>

  <!-- attr: checked_at date, uses flatpickr -->
  <div class="form-row">
    <div class="col-6 form-group">
      <%= form.label :check_at %>
      <div class="input-group mb-3">
        <%= form.text_field :check_at, id: 'check-date',
                            class: 'form-control bg-white-flatpickr' %>
        <div class="input-group-append">
          <span class="input-group-text" id="basic-addon2"><i class="far fa-calendar-alt"></i></span>
        </div>
      </div>
    </div>
  </div>

  <!-- attr: handle -->
  <div class="form-row">
    <div class="col-6 form-group">
      <%= form.label :handle %>
      <%= form.text_field :handle, class: 'form-control' %>
    </div>
  </div>

  <!-- attr: description text box -->
  <div class="form-row">
    <div class="form-group col-md-9">
      <%= form.label :description %>
      <br>
      <div>
        <% num_rows = ux_textarea_rows(checkpoint.description, max_rows=5) %>
        <%= form.text_area :description, rows: num_rows, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Ok", class: "btn btn-outline-success" %>
  </div>

<% end %>

app/views/checkpoints/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<h2>Edit checkpoint</h2>

<%= render 'form', checkpoint: @checkpoint %>

<!-- nav: breadcrumbs -->
<% bc1 = ['All checkpoints', checkpoints_path] %>
<%= render 'shared/breadcrumbs', cur_page: 'Edit checkpoint', crumbs: bc1 %>

    </div>
  </div>
</div>

app/views/checkpoints/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<span id="notice"><%= notice %></span>

<h3>All checkpoints</h3>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Check at</th>
      <th>Handle</th>
      <th>Description</th>
      <th>School</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @checkpoints.each do |checkpoint| %>
      <tr>
        <td><%= checkpoint.id %></td>
        <td><%= checkpoint.check_at %></td>
        <td><%= checkpoint.handle %></td>
        <td><%= truncate(checkpoint.description, length: 20) %></td>
        <td><%= checkpoint.school_id %></td>
        <td class="small">
          <%= link_to 'Show', checkpoint %>
          |
          <%= link_to 'Edit', edit_checkpoint_path(checkpoint) %>
          |
          <%= link_to 'Destroy', checkpoint, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p class="mt-4">
  <%= link_to '+ New Checkpoint', new_checkpoint_path, class: "btn btn-outline-success" %>
</p>

<p>
  Past checkpoints (<%= @past_checkpoints.count %>):
</p>
<ul>
  <% @past_checkpoints.each do |each_checkpoint| %>
    <li>
      <%= each_checkpoint.check_at %>,
      id=<%= each_checkpoint.id %>,
      handle=<%= each_checkpoint.handle %>,
      <%= link_to 'edit', edit_checkpoint_path(each_checkpoint) %>
    </li>
  <% end %>
</ul>


<!-- nav: breadcrumbs -->
<%= render 'shared/breadcrumbs', cur_page: 'All checkpoints' %>

    </div>
  </div>
</div>

app/views/checkpoints/new.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<h2 class="mb-3">New checkpoint</h2>

<%= render 'form', checkpoint: @checkpoint %>

<!-- nav: breadcrumbs -->
<% bc1 = ['All checkpoints', checkpoints_path] %>
<%= render 'shared/breadcrumbs', cur_page: 'New checkpoint', crumbs: bc1 %>

    </div>
  </div>
</div>

app/views/checkpoints/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<p id="notice"><%= notice %></p>

<h3 class="mb-3">Show Checkpoint</h3>

<p>
  <strong>Check at:</strong>
  <%= @checkpoint.check_at %>
</p>

<p>
  <strong>Duration days:</strong>
  <%= @checkpoint.duration_days %>
</p>

<p>
  <strong>Handle:</strong>
  <%= @checkpoint.handle %>
</p>

<p>
  <strong>Description:</strong>
  <%= @checkpoint.description %>
</p>

<p>
  <strong>School:</strong>
  <%= @checkpoint.school_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @checkpoint.student_id %>
</p>

<!-- nav: breadcrumbs -->
<% bc1 = ['All checkpoints', checkpoints_path] %>
<%= render 'shared/breadcrumbs', cur_page: 'Show checkpoint', crumbs: bc1 %>

    </div>
  </div>
</div>