config/routes.rb
Rails.application.routes.draw do

  resources :playground_stuffs
  root 'static_pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      patch :increment
      patch :clear
    end
    resources :life_events, only: [:index, :new, :create]
  end

  resources :life_events, only: [:show, :edit, :update, :destroy]
  resources :students
  resources :journals, only: [:index, :show]
  resources :journal_entries

  resources :schools
  resources :checkpoints
  resources :goal_steps
  resources :goals

  resources :playgroundstuffs, only: [:index, :show, :edit, :update]

  get 'import_csv', to: 'users#import_csv'
  patch 'import_csv', to: 'users#update_csv'
  get 'import_csv2', to: 'users#import_csv2'
  patch 'import_csv2', to: 'users#update_csv2'

  get 'chart_fun', to: 'users#chart_fun'

  get 'calendar_test', to: 'users#calendar_test'
  get 'my_calendar_test', to: 'users#my_calendar_test'

  get 'hook', to: 'static_pages#hook'
  get 'run_hook', to: 'static_pages#run_hook'

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :school
  has_many :life_events
  has_many :journal_entries

  validates :email, presence: true
  validates :school_id, presence: true

  def self.all_users
    User.order( "name ASC")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require "csv"
  include UsersHelper

  before_action :set_user, only: [:show, :edit, :update, :destroy,
                                  :increment, :clear, :new_life_event]

  # GET /root
  def root
  end

  # GET /users
  def index
    # default is sort by name, ascending
    @sort_by = "nA"
    @sort_by = params["sort_by"] if params["sort_by"].present?

    # set sorts for next call
    @name_sort = "nA"
    @email_sort = "eA"
    @stars_sort = "sA"

    case @sort_by
    when "nA"
      @users = User.order("name ASC")
      @name_sort = "nD"
    when "nD"
      @users = User.order("name DESC")
    when "eA"
      @users = User.order("email ASC")
      @email_sort = "eD"
    when "eD"
      @users = User.order("email DESC")
    when "sA"
      @users = User.order("stars DESC")
      @stars_sort = "sD"
    when "sD"
      @users = User.order("stars ASC")
    else
      @users = User.order("name ASC")
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @schools = School.all_schools
  end

  # GET /users/1/edit
  def edit
    @user.party_started_at = Time.zone.now if @user.party_started_at.nil?
    @schools = School.all_schools
  end

  # POST /users
  def create
    @user = User.new(user_params)

    # update party start and end times
    dt_hash = ux_calc_party_times(params[:user][:party_started_at],
                                  params[:user][:party_start_time],
                                  params[:user][:party_duration])
    @user.party_started_at = dt_hash[:start]
    @user.party_ended_at = dt_hash[:end]

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    # update party start and end times
    dt_hash = ux_calc_party_times(params[:user][:party_started_at],
                                  params[:user][:party_start_time],
                                  params[:user][:party_duration])
    @user.party_started_at = dt_hash[:start]
    @user.party_ended_at = dt_hash[:end]
    @user.save

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PATCH /users/1/increment
  def increment
    @user.increment!( :stars)
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Increment ok'}
      format.js
    end
  end

  # PATCH /users/1/clear
  def clear
    @user.stars = 0
    @user.save
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Stars are now zero'}
      format.js
    end
  end

  # GET /users/1/import_csv
  def import_csv
  end

  # GET /users/1/import_csv
  def update_csv
    @user_csv_guy = UserCsvGuy.new(params[:csv_data])
    respond_to do |format|
      format.js
    end
  end

  # GET /users/1/import_csv2
  def import_csv2
  end

  # GET /users/1/update_csv2
  def update_csv2
    # really add the CSV data to the session here
    @user_csv_guy = UserCsvGuy.new(params[:import_str])
    @user_csv_guy.accept_rows

    redirect_to import_csv_path, notice: 'CSV data accepted'
  end

  # GET /users/1/chart_fun
  def chart_fun
  end

  # GET /users/1/my_calendar_test
  def my_calendar_test
    @my_calendar = MySimpleCalendar.new(params)
    d1 = Date.current - 1.day
    d2 = Date.current - 1.week
    d3 = Date.current + 1.month
    list1 = [d1, d2, d3]
    @my_calendar.add_item_dates(list1)
    update_blather(@my_calendar.selected_date)
  end

  # GET /users/1/calendar_test
  def calendar_test
    @blather = if params["the_date"]
                 "Date selected is " + params["the_date"]
               else
                 "Nothing to say, Bill"
               end

    item1 = CalendarItem.new( Date.new(2021, 10, 15).to_datetime, "TY due!")
    item2 = CalendarItem.new( Date.new(2021, 10, 22), "Trip to Portland, ME")
    @events = []
    @events << item1 << item2
    d1 = params["start_date"].to_date if params["start_date"]
    d1 ||= Date.today
    test = Util.month_name(d1)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user)
            .permit(:name, :email, :school_id, :stars, :comment)
    end

    def update_blather(the_date)
      if the_date
        @blather = "Selected date is " + the_date.strftime("%b %-d, %Y")
      else
        @blather = "No date selected yet"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def ux_textarea_rows(str, min_rows = 2, max_rows = 5)
    x = 0
    x = str.lines.count + 1 if str.present?
    x = min_rows if x < min_rows # at least min rows
    x = max_rows if x > max_rows # no more than max rows
    x
  end

  def ux_party_duration_choices
    ['5 minutes', '15 minutes', '30 minutes', '45 minutes', 
      '1 hour', '2 hours', '4 hours', '6 hours', '8 hours']
  end

  def ux_calc_party_times(date_str, time_str, duration_str)
    # get the start date in the user's time zone
    Time.zone = "Central Time (US & Canada)"
    dt1 = Time.zone.parse(date_str)

    # get the start time, fix the datetime to use it
    time1 = Time.parse(time_str)
    dt_start = dt1.change( hour: time1.hour, min: time1.min)

    # add the duration string to get the end datetime
    dt_end = case duration_str
              when '5 minutes'
                dt_start + 5.minutes
              when '15 minutes'
                dt_start + 5.minutes
              when '30 minutes' 
                dt_start + 5.minutes
              when '45 minutes' 
                dt_start + 5.minutes
              when '1 hour'
                dt_start + 1.hour
              when '2 hours'
                dt_start + 2.hours
              when '4 hours'
                dt_start + 4.hours
              when '6 hours'
                dt_start + 6.hours
              when '8 hours'
                dt_start + 8.hours
              end
    
    # stuff our datetimes into a hash and return
    { start: dt_start, end: dt_end }
    end
end

app/views/users/_ajax_import_csv1.html.erb
<!-- Ajax code for import CSV, part 1 -->
<!-- This code is loaded with the import CSV page -->
<p>
  Step 1: Enter data. Copy-paste your CSV data.
</p>

<%= form_with(url: import_csv_path, method: 'patch', remote: true) do |form| %>

  <!-- text area for the CSV copy-paste -->
  <div class="field">
    <%= form.text_area :csv_data, rows: 10,
                       :placeholder => "my default value",
                       :value => "Email,Party time,Stars\n",
                       style: "padding: 8px; width: 100%; border-radius: 8px;" %>
  </div>

  <!-- ok button -->
  <div class="actions mt-3">
    <%= form.submit "1. Enter data", class: "btn btn-outline-secondary" %>
    &nbsp;
    <%= link_to "2. Accept", "#", class: "btn btn-outline-secondary disabled" %>
    <%= link_to "Clear", import_csv_path, class: "btn btn-outline-primary float-right" %>
  </div>

 <% end %>

app/views/users/_ajax_import_csv2.html.erb
<!-- Ajax code for import CSV, part 2 -->
<!-- This code is loaded after "Enter data" button is pressed -->
<p>
  Step 2: Accept data.
</p>

<div class="border border-success rounded p-2 div-hb-fade"
     style="background-color: GhostWhite; min-height: 14rem;">
  <!-- start with the CSV header -->
  &nbsp; &nbsp; &nbsp
  Email,Party time,Stars
  <br>
  <!-- show each row-->
  <% @user_csv_guy.array_of_rows.each_with_index do |each_row, index| %>
    <%= index+1 %>:
    &nbsp;
    <span class="text-muted"><%= @user_csv_guy.row_str(each_row) %></span>
    &nbsp;
    <span class="<%= @user_csv_guy.row_bootstrap_css(each_row) %>">
      <%= @user_csv_guy.row_full_comment(each_row) %>
    </span>
    <br>
  <% end %>
</div>

<%= form_with(url: import_csv2_path, method: 'patch', local: true) do |form| %>
  <p class="mt-3">
    <% if @user_csv_guy.num_acceptable_rows > 0 %>
      You can accept changes for
      <span class="text-success font-weight-bold">
        <%= pluralize( @user_csv_guy.num_acceptable_rows, "user") %>
      </span>
    <% else %>
      There are no valid changes to accept.
    <% end %>
  </p>

  <!-- ok button -->
  <div class="actions mt-3">
    <%= hidden_field_tag 'import_str', @user_csv_guy.import_str %>
    <%= hidden_field_tag 'num_acceptable', @user_csv_guy.num_acceptable_rows %>
    <%= link_to "1. Enter data", "#", class: "btn btn-outline-secondary disabled" %>
    &nbsp;
    <% if @user_csv_guy.num_acceptable_rows > 0 %>
      <%= form.submit "2. Accept", class: "btn btn-outline-success" %>
    <% else %>
      <%= link_to "2. Accept", "#", class: "btn btn-outline-success disabled" %>
    <% end %>

    <%= link_to "Clear", import_csv_path, class: "btn btn-outline-primary float-right" %>
  </div>

 <% end %>
</div>

app/views/users/_calendar_body.html.erb
<!--
  Partial: calendar_boy
  Guts of the MyCalendar body
-->
<div class="msc-calendar">
  <div class="calendar-heading text-center">
    <%= link_to '< Prev', url_for(@my_calendar.params_for_prev), class: "float-left" %>

    <span class="title"><%= t(@my_calendar.title) %></span>

    <%= link_to 'Next >', url_for(@my_calendar.params_for_next), class: "float-right" %>
  </div>

  <table class="table border-1">

    <!-- table header: show days-of-the-week names: Sun, Mon, ...Sat -->
    <thead>
      <tr>
        <% @my_calendar.day_names.each do |each_name| %>
          <th><%= each_name %></th>
        <% end %>
      </tr>
    </thead>

    <!-- table body: show the days in 7 day (one week) slices -->
    <tbody>
      <% @my_calendar.date_range.each_slice(7) do |each_week| %>
        <tr>
          <% each_week.each do |each_day| %>
            <% if @my_calendar.is_cur_month(each_day) %>
            <% css1 = "weekend" if @my_calendar.is_weekend(each_day) %>
              <td class="<%= css1 %>">
                <%= link_to url_for(@my_calendar.params_for_selected_date(each_day)) do %>
                  <% css2 = @my_calendar.css_classes(each_day) %>
                  <span class="<%= css2 %>"><%= each_day.day %></span>
                <% end %>
              </td>
            <% else %>
              <td>
                <!-- empty if day is not during this month -->
              </td>
            <% end %> <!-- if day is in this month-->
          <% end %> <!-- for each day -->
        </tr>
      <% end %>

      <% if @my_calendar.num_weeks < 6 %>
        <tr>
          <% for j in 1..7 do %>
            <td> &nbsp; </td>
          <% end %>
        </tr>
      <% end %>

    </tbody>
  </table>

  <!-- text: formatting key-->
  <p class="text-hb-md">
    Calendar:
    &nbsp;
    <%= link_to 'Today', url_for(@my_calendar.params_for_jump(Date.current)),
                                   class: "btn btn-sm btn-outline-secondary" %>
    <% if @my_calendar.selected_date %>
      &nbsp;
      <%= link_to 'Clear selection', url_for(@my_calendar.params_for_clear_selected_date()),
                                     class: "btn btn-sm btn-outline-secondary" %>
    <% end %>
  </p>
  <p class="text-hb-md">
    Key to days formatting: <span style="color: red">today</span>,
    <span style="background-color: lightgray; padding: 2px;">selected</span>, <u>activity</u>
  </p>
</div>

app/views/users/_calendar_items.html.erb
<!--
  Parital: calendar_items
  Display calendar items on the selected date
-->
<% today = Date.current %>
<% birthday = Date.new(today.year, 2, 27) %>

<% if @my_calendar.selected_date %>

  <h5>
    <% nice_date = @my_calendar.selected_date.strftime("%a %b %-d") %>
    Activity on <%= nice_date %>
  </h5>

  <ul class="text-hb-md ul-spacer" style="list-style-type:circle">
    <li>
      Checkpoint - meet with parents, <%= link_to 'view', users_url %>
    </li>
    <li>
      Life event - change in medications, <%= link_to 'view', users_url %>
    </li>
    <li>
      Session with WilliamT @ 10:15 am - Goal3/Obj1 Improve flash cards and other...,
      <%= link_to 'view', users_url %>
    </li>
    <li>
      Session with Amy P @ 11:20 am - Goal2/Ben2 50% fluency in Spanish quizzes,
      <%= link_to 'view', users_url %>
    </li>
  </ul>
  <p class="text-hb-md">
    Actions: &nbsp;
    <%= link_to '+ New life event', users_url, class: "btn btn-sm btn-outline-success" %>
  </p>
<% else %>
  <p class="text-hb-lg">
    <i class="fa fa-info-circle text-primary pr-2"></i>
    Select calendar to see student activity on that date.
  </p>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

  <%= render 'shared/form_error', the_object: user %>

  <div class="form-row">
    <!-- name attr -->
    <div class="form-group col-md-6">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <!-- email attr -->
    <div class="form-group col-md-6">
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <!-- attr: school -->
    <div class="form-group col-md-6">
      <%= form.label :school_id %>
      <%= form.select :school_id, @schools.map{ |c| [c.name, c.id]},
                                  { }, { :class => 'form-control' } %>
    </div>
  </div>

  <!-- stars attr -->
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :stars %>
      <%= form.number_field :stars, class: 'form-control' %>
    </div>
  </div>

<style>
  .bg-white-flatpickr { background-color: white !important; }
</style>

  <!-- party started_at attr, uses flatpickr to choose date -->
  <div class="row">
    <div class="col-md-4">
      <%= form.label "Party date" %>
      <div class="input-group mb-3">
        <%= form.text_field :party_started_at, id: 'party-date',
                            class: 'form-control bg-white-flatpickr' %>
        <div class="input-group-append">
          <span class="input-group-text" id="basic-addon2"><i class="far fa-calendar-alt"></i></span>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <%= form.label "Party start time" %>
      <div class="input-group mb-3">
        <%= form.text_field :party_start_time, id: 'party-time', value: "9:00",
                            class: 'form-control bg-white-flatpickr' %>
        <div class="input-group-append">
          <span class="input-group-text" id="basic-addon2"><i class="far fa-clock"></i></span>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <%= form.label "Duration" %>
      <%= form.select :party_duration,
                      options_for_select(ux_party_duration_choices(), '30 minutes'),
                      {}, class: "form-control" %>
    </div>
  </div>

  <!-- comment attr, a text box -->
  <div class="form-row">
    <div class="form-group col-md-9">
      <%= form.label :comment %>
      <br>
      <div>
        <% num_rows = ux_textarea_rows(user.comment, max_rows=5) %>
        <%= form.text_area :comment, rows: num_rows, class: 'form-control' %>
      </div>
    </div>
  </div>

  <!-- ok button -->
  <div class="actions">
    <%= form.submit "Update user", class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= user.name %></td>
  <td class="d-none d-lg-table-cell"><%= user.email %></td>
  <td id="stars-<%= user.id %>"><%= user.stars %></td>
  <td class="d-none d-lg-table-cell text-play-sm">
    <% if user.party_started_at %>
      <%= user.party_started_at.strftime("%m/%d/%Y %H:%M") %>
    <% else %>
      Bill: BAD party_started_at, it's missing!
    <% end %>
  </td>
  <td class="text-play-sm text-muted">
    [
      <%= link_to 'Inc', increment_user_path(user),
                         method: :patch, remote: true %>,
      <%= link_to 'Clr', clear_user_path(user),
                         method: :patch, remote: true %>
    ]
  </td>
  <td class="text-play-sm">
    <%= link_to 'Show', user %> |
    <%= link_to 'Edit', edit_user_path(user) %> |
    <%= link_to 'Destroy', user,
                method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/users/chart_fun.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<p id="notice"><%= notice %></p>

<h2 class="mb-3">Chart fun</h2>

<p>
  Hey Bill - insert chart.js example here.
</p>
<p>
  Hi again. Here's a <small>small change</small> for a push/deploy test.
</p>
<p class="text-info">
  Second try...info text.
</p>

<%= link_to '< Index', users_path %>
<br><br>

<!-- new chart.js V3.0 example -->
<!-- Source: www.chartjs.org/docs/latest/getting-started/usage.html -->

<style>
  .chart-wrapper { position:relative; height: 400px; width: 100%; }
  .chart-canvas { width: 100% !important; }
</style>

<div class="chart-wrapper">
  <canvas id="myChart" class="chart-canvas"></canvas>
</div>

    </div>
  </div>
</div>

<script>

  var ctx = document.getElementById('myChart').getContext('2d');

  var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
  });

</script>

app/views/users/clear.js.erb
the_id = "stars-" + <%= @user.id %>;
document.getElementById(the_id).innerHTML = "<%= @user.stars %>";

app/views/users/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">


<h2 class="mb-3">
  Edit User

  <small class="float-right">
    <!-- Edit User is where life events can be added to an existing user -->
    <%= link_to '+ New life event', new_user_life_event_path(@user),
                class: "btn btn-outline-success float-right mt-2 mr-2" %>
  </small>
</h2>

<%= render 'form', user: @user %>

<!-- nav: breadcrumbs -->
<% bc1 = ['All users', users_path] %>
<%= render 'shared/breadcrumbs', cur_page: 'Edit user', crumbs: bc1 %>


    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<span id="notice"><%= notice %></span>

<h3>All users</h3>
<p class="text-muted my-3">
  Click on the column heading to sort
</p>

<style>
  .border-sorted {
    padding: 8px;
    border: 1px solid RebeccaPurple;
    border-radius: 8px;
    background-color: ghostwhite;
  }
  .border-not-sorted {
    padding: 8px;
    border: 1px solid white;
    border-radius: 8px;
    background-color: white;
  }
</style>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>
        <%= link_to 'Name', users_path(sort_by: "nD"), remote: true,
                            id: "name-link", class: "border-sorted" %>
      </th>
      <th class="d-none d-lg-table-cell"><%= link_to 'Email', users_path(sort_by: "eA"), remote: true,
                               id: "email-link",
                               class: "border-not-sorted" %></th>
      <th><%= link_to 'Stars', users_path(sort_by: "sA"), remote: true,
                               id: "stars-link", class: "border-not-sorted" %></th>
      <th class="d-none d-lg-table-cell">Party time</th>
      <th>+/-</th>
      <th class="text-center">Actions</th>
    </tr>
  </thead>

  <tbody id="users-body">
    <!-- Rails magic renders user partial foreach user in the collection -->
    <%= render @users %>
  </tbody>
</table>

<p class="mt-4">
  <%= link_to '+ New User', new_user_path, class: "btn btn-outline-success" %>
</p>

<!-- get the js to support this button -->

<!-- nav: breadcrumbs -->
<%= render 'shared/breadcrumbs', cur_page: 'All users' %>


    </div>
  </div>
</div>

<%= javascript_pack_tag 'hello', 'data-turbolinks-track': 'reload' %>

app/views/users/index.js.erb
/* render table with newly-sorted list */
document.getElementById("users-body").innerHTML = "<%= j render @users %>";

/* update all table heading links, so that ascend/descend sort works */
var sort_char = "<%= @sort_by %>".charAt(0);

var name_link = document.getElementById("name-link");
name_link.href = "<%= users_path(sort_by: "#{@name_sort}") %>";
name_link.classList.remove("border-sorted");
name_link.classList.remove("border-not-sorted");
if( sort_char == "n") {
  name_link.classList.add("border-sorted");
} else {
  name_link.classList.add("border-not-sorted");
}

var email_link = document.getElementById("email-link");
email_link.href = "<%= users_path(sort_by: "#{@email_sort}") %>";
email_link.classList.remove("border-sorted");
email_link.classList.remove("border-not-sorted");
if( sort_char == "e") {
  email_link.classList.add("border-sorted");
} else {
  email_link.classList.add("border-not-sorted");
}

var stars_link = document.getElementById("stars-link");
stars_link.href = "<%= users_path(sort_by: "#{@stars_sort}") %>"
stars_link.classList.remove("border-sorted");
stars_link.classList.remove("border-not-sorted");
if( sort_char == "s") {
  stars_link.classList.add("border-sorted");
} else {
  stars_link.classList.add("border-not-sorted");
}

app/views/users/my_calendar_test.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<h3 class="mb-3">My Calendar test</h2>

<div class="row mt-4">

  <!-- col: the calendar table goes in the top/left -->
  <div class="col-12 col-lg-6">
    <%= render "calendar_body" %>
  </div>

  <!-- col: calendar items on the selected date...and more! -->
  <div class="col-12 col-lg-6 pt-4 pl-4">
    <%= render "calendar_items" %>
  </div>
</div>

<br>
<%= link_to '< Index', users_path %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<span id="notice"><%= notice %></span>

<h3 class="mb-3">Show user</h3>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>School:</strong>
  <%= @user.school.name %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @user.stars %>
</p>

<p>
  <strong>Party started_at:</strong>
  <%= @user.party_started_at %>
</p>

<p>
  <strong>Party ended_at:</strong>
  <%= @user.party_ended_at %>
</p>

<p>
  <strong>Comment:</strong>
  <div class="ml-5 p-3 border rounded">
    <%= simple_format @user.comment %>
  </div>
</p>

<p class="mt-4">
  <strong>Life events (<%= @user.life_events.count %>):</strong>
</p>
<p class="text-muted">
  <% if @user.life_events.present? %>
    Ordered by date
  <% else %>
    This user has no life events.
  <% end %>
</p>
<ul>
  <%= render LifeEvent.all_for_user(@user) %>
</ul>

<!-- nav: breadcrumbs -->
<% bc1 = ['All users', users_path] %>
<%= render 'shared/breadcrumbs', cur_page: 'Show user', crumbs: bc1 %>

    </div>
  </div>
</div>

app/views/users/update_csv.js.erb
var import_div = document.getElementById("import-csv-div");
import_div.innerHTML = "<%= j render 'ajax_import_csv2' %>";