config/routes.rb
Rails.application.routes.draw do

  resources :playground_stuffs
  root 'static_pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      patch :increment
      patch :clear
    end
    resources :life_events, only: [:index, :new, :create]
  end

  resources :life_events, only: [:show, :edit, :update, :destroy]
  resources :students
  resources :journals, only: [:index, :show]
  resources :journal_entries

  resources :schools
  resources :checkpoints
  resources :goal_steps
  resources :goals

  resources :playgroundstuffs, only: [:index, :show, :edit, :update]

  get 'import_csv', to: 'users#import_csv'
  patch 'import_csv', to: 'users#update_csv'
  get 'import_csv2', to: 'users#import_csv2'
  patch 'import_csv2', to: 'users#update_csv2'

  get 'chart_fun', to: 'users#chart_fun'

  get 'calendar_test', to: 'users#calendar_test'
  get 'my_calendar_test', to: 'users#my_calendar_test'

  get 'hook', to: 'static_pages#hook'
  get 'run_hook', to: 'static_pages#run_hook'

end

app/models/school.rb
class School < ApplicationRecord
  has_many :students
  has_many :users
  has_many :checkpoints

  # returns all schools
  def self.all_schools
    School.all
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: %i[ show edit update destroy ]

  # GET /schools or /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1 or /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools or /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: "School was successfully created." }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1 or /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: "School was successfully updated." }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1 or /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: "School was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def school_params
      params.require(:school).permit(:name, :handle, :color)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>

  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="col-6 form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-row">
    <div class="col-6 form-group">
      <%= form.label :handle %>
      <%= form.text_field :handle, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="col-6 form-group">
      <%= form.label :color %>
      <%= form.text_field :color, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Ok", class: "btn btn-outline-secondary" %>
  </div>

<% end %>

app/views/schools/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<h2>Edit school</h2>

<%= render 'form', school: @school %>

<!-- nav: breadcrumbs -->
<% bc1 = ['All schools', schools_path] %>
<%= render 'shared/breadcrumbs', cur_page: 'Edit school', crumbs: bc1 %>

    </div>
  </div>
</div>

app/views/schools/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<p id="notice"><%= notice %></p>

<h2 class="mb-3">Schools</h1>

<p class="text-muted">
  There
  <%= pluralize_is_are(@schools.count) %>
  <%= pluralize( @schools.count, "school") %>.
</p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Handle</th>
      <th>Students</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |each_school| %>
      <tr>
        <td><%= each_school.name %></td>
        <td>
          <span style="color: <%= each_school.color %>;">
            <%= each_school.handle %>
          </span>
        </td>
        <td>
          <%= Student.all_students(each_school).count %>
        </td>
        <td>
          <%= link_to 'Show', each_school %> &nbsp; | &nbsp;
          <%= link_to 'Edit', edit_school_path(each_school) %> &nbsp; | &nbsp;
          <%= link_to 'Destroy', each_school, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- button: new school -->
<%= link_to '+ New school', new_school_path, class: "mt-3 btn btn-outline-success" %>

<!-- nav: breadcrumbs -->
<%= render 'shared/breadcrumbs', cur_page: 'All schools' %>

    </div>
  </div>
</div>

app/views/schools/new.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<h2 class="mb-3">New school</h2>

<%= render 'form', school: @school %>

<!-- nav: breadcrumbs -->
<% bc1 = ['All schools', schools_path] %>
<%= render 'shared/breadcrumbs', cur_page: 'New school', crumbs: bc1 %>

    </div>
  </div>
</div>

app/views/schools/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

<p id="notice"><%= notice %></p>

<h3 class="mb-3 border-bottom">Show School</h3>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Handle:</strong>
  <%= @school.handle %>
</p>

<p>
  <strong>Color:</strong>
  <span style="color: <%= @school.color %>;"><%= @school.color %></span>
</p>

<!-- nav: breadcrumbs -->
<% bc1 = ['All schools', schools_path] %>
<%= render 'shared/breadcrumbs', cur_page: 'Show school', crumbs: bc1 %>

    </div>
  </div>
</div>